'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PMD-2021-889651-7556")>  _
        Public Property UserLic() As String
            Get
                Return CType(Me("UserLic"),String)
            End Get
            Set
                Me("UserLic") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Jaime M. Roza Pedreira")>  _
        Public Property UserName() As String
            Get
                Return CType(Me("UserName"),String)
            End Get
            Set
                Me("UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MS Access2010/19")>  _
        Public Property DBType() As String
            Get
                Return CType(Me("DBType"),String)
            End Get
            Set
                Me("DBType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PMovilD")>  _
        Public Property DBName() As String
            Get
                Return CType(Me("DBName"),String)
            End Get
            Set
                Me("DBName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\PMovilD")>  _
        Public Property PathAPP() As String
            Get
                Return CType(Me("PathAPP"),String)
            End Get
            Set
                Me("PathAPP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C\PMovilD")>  _
        Public Property AccPath() As String
            Get
                Return CType(Me("AccPath"),String)
            End Get
            Set
                Me("AccPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2021-09-15")>  _
        Public Property InstallDte() As Date
            Get
                Return CType(Me("InstallDte"),Date)
            End Get
            Set
                Me("InstallDte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("jrozap")>  _
        Public Property UserID() As String
            Get
                Return CType(Me("UserID"),String)
            End Get
            Set
                Me("UserID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Admin")>  _
        Public Property UserType() As String
            Get
                Return CType(Me("UserType"),String)
            End Get
            Set
                Me("UserType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dsn=PMovilD - Postgre;database=pmovild;server=127.0.0.1;port=5432;uid=root;sslmod"& _ 
            "e=disable;readonly=0;protocol=7.4;fakeoidindex=0;showoidcolumn=0;rowversioning=0"& _ 
            ";showsystemtables=0;fetch=100;unknownsizes=0;maxvarcharsize=255;maxlongvarcharsi"& _ 
            "ze=8190;debug=0;commlog=0;usedeclarefetch=0;textaslongvarchar=1;unknownsaslongva"& _ 
            "rchar=0;boolsaschar=1;parse=0;lfconversion=1;updatablecursors=1;trueisminus1=0;b"& _ 
            "i=0;byteaaslongvarbinary=1;useserversideprepare=1;lowercaseidentifier=0;d6=-101;"& _ 
            "optionalerrors=0;xaopt=1")>  _
        Public Property MRSDataPG() As String
            Get
                Return CType(Me("MRSDataPG"),String)
            End Get
            Set
                Me("MRSDataPG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Driver={MariaDB ODBC 3.1 Driver};uid=root;passwd=jr632504$;description=PMovilD-Ma"& _ 
            "riaDB;tcpip=1;server=127.0.0.1;database=pmovild;port=3306")>  _
        Public Property MRSDataMDB() As String
            Get
                Return CType(Me("MRSDataMDB"),String)
            End Get
            Set
                Me("MRSDataMDB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Driver={Microsoft Access Driver (*.mdb, *.accdb)};dbq=D:\Documentos\PMovilD\PMovi"& _ 
            "lD.accdb;defaultdir=D:\Documentos\PMovilD;driverid=25;fil=MS Access;filedsn=D:\D"& _ 
            "ocumentos\PMovilD\PMovilD-MSAccess.dsn;maxbuffersize=2048;maxscanrows=8;pagetime"& _ 
            "out=5;safetransactions=0;threads=3;uid=admin;usercommitsync=Yes")>  _
        Public Property MRSDataAcc() As String
            Get
                Return CType(Me("MRSDataAcc"),String)
            End Get
            Set
                Me("MRSDataAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RedVital")>  _
        Public Property CiaName() As String
            Get
                Return CType(Me("CiaName"),String)
            End Get
            Set
                Me("CiaName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\Documentos\PMovilD\Resources\redvital1.png")>  _
        Public Property CiaLogoP() As String
            Get
                Return CType(Me("CiaLogoP"),String)
            End Get
            Set
                Me("CiaLogoP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2021-09-15")>  _
        Public Property PMovilDF() As Date
            Get
                Return CType(Me("PMovilDF"),Date)
            End Get
            Set
                Me("PMovilDF") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Driver={Microsoft Access Driver (*.mdb, *.accdb)};dbq=D:\Documentos\PMovilD\PMovi"& _ 
            "lD.accdb;defaultdir=D:\Documentos\PMovilD;driverid=25;fil=MS Access;filedsn=D:\D"& _ 
            "ocumentos\PMovilD\PMovilD-MSAccess.dsn;maxbuffersize=2048;maxscanrows=8;pagetime"& _ 
            "out=5;safetransactions=0;threads=3;uid=admin;usercommitsync=Yes")>  _
        Public ReadOnly Property PMDConnect() As String
            Get
                Return CType(Me("PMDConnect"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("000")>  _
        Public Property AsientoN() As String
            Get
                Return CType(Me("AsientoN"),String)
            End Get
            Set
                Me("AsientoN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2021-09-30")>  _
        Public Property CierreD() As Date
            Get
                Return CType(Me("CierreD"),Date)
            End Get
            Set
                Me("CierreD") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Driver={MariaDB ODBC 3.1 Driver};uid=root;passwd=jr632504$;description=PMovilD-Ma"& _ 
            "riaDB;tcpip=1;server=127.0.0.1;database=pmovild;port=3306")>  _
        Public ReadOnly Property pmovildConnectionString() As String
            Get
                Return CType(Me("pmovildConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property UserIDMDB() As String
            Get
                Return CType(Me("UserIDMDB"),String)
            End Get
            Set
                Me("UserIDMDB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property UserIDPG() As String
            Get
                Return CType(Me("UserIDPG"),String)
            End Get
            Set
                Me("UserIDPG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("admin")>  _
        Public Property UserIDAcc() As String
            Get
                Return CType(Me("UserIDAcc"),String)
            End Get
            Set
                Me("UserIDAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("jr632504$")>  _
        Public Property passwdMDB() As String
            Get
                Return CType(Me("passwdMDB"),String)
            End Get
            Set
                Me("passwdMDB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("jmrp6122625")>  _
        Public Property passwdPG() As String
            Get
                Return CType(Me("passwdPG"),String)
            End Get
            Set
                Me("passwdPG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property passwdAcc() As String
            Get
                Return CType(Me("passwdAcc"),String)
            End Get
            Set
                Me("passwdAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
        Public Property MDBipV4() As String
            Get
                Return CType(Me("MDBipV4"),String)
            End Get
            Set
                Me("MDBipV4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
        Public Property PGipV4() As String
            Get
                Return CType(Me("PGipV4"),String)
            End Get
            Set
                Me("PGipV4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PMovilD-MariaDB")>  _
        Public Property dsnMDB() As String
            Get
                Return CType(Me("dsnMDB"),String)
            End Get
            Set
                Me("dsnMDB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PMovilD-PostgreSQL")>  _
        Public Property dsnPG() As String
            Get
                Return CType(Me("dsnPG"),String)
            End Get
            Set
                Me("dsnPG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PMovilD-MSAccess")>  _
        Public Property dsnAcc() As String
            Get
                Return CType(Me("dsnAcc"),String)
            End Get
            Set
                Me("dsnAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PMovilD-MSAccess")>  _
        Public Property currDSN() As String
            Get
                Return CType(Me("currDSN"),String)
            End Get
            Set
                Me("currDSN") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dsn=PMovilD - MSAccess 2010/2019;dbq=D:\Documentos\PMovilD\PMovilD.accdb;driverid"& _ 
            "=25;fil=MS Access;maxbuffersize=2048;pagetimeout=5")>  _
        Public ReadOnly Property ConnectionString() As String
            Get
                Return CType(Me("ConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PMovilD.My.MySettings
            Get
                Return Global.PMovilD.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
